# Generated by Django 2.2.9 on 2020-01-31 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200130_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(null=True, upload_to='static/blog/image/'),
        ),
    ]
