# Generated by Django 2.2.9 on 2020-01-31 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_post_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/blog/image/'),
        ),
    ]
