# Generated by Django 2.2.9 on 2020-02-06 14:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200206_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='chanel',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
