# Generated by Django 2.2.9 on 2020-02-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_chanel_timestamp'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chanel',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AlterField(
            model_name='post',
            name='post_pic',
            field=models.ImageField(blank=True, height_field='30%', null=True, upload_to='post_picd', width_field='30%'),
        ),
    ]
