# Generated by Django 2.2.9 on 2020-02-06 17:08

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20200206_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='downvote',
            field=models.ManyToManyField(blank=True, related_name='comment_downvote', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='comment',
            name='upvote',
            field=models.ManyToManyField(blank=True, related_name='comment_upvote', to=settings.AUTH_USER_MODEL),
        ),
    ]
